### ISSUE TITLE
Feature Request: Allow release to run build commands and add artifacts to the release

### ISSUE THREAD

**Issue by frodopwns** [drud/rlsr#2]
Either assume a standard like `make build` or allow the user to specify a `build` field for each repository in a release.

This would look like:

```
- name: TestRelease
  type: patch
  org: your_org
  repos:
    - name: releaser
      build: make all
```

The build would be assumed to save artifacts in the .artifacts directory.

The rlsr tool would then attach everything left in .artifacts to the release.
